use crate::ingest::AssetKind;

pub fn beautify(kind: AssetKind, content: &str) -> String {
    match kind {
        AssetKind::Html => beautify_html(content),
        AssetKind::JavaScript => beautify_javascript(content),
        _ => content.to_string(),
    }
}

// ── HTML beautifier ───────────────────────────────────────────────────────────

fn beautify_html(content: &str) -> String {
    let mut out = String::new();
    let mut indent = 0usize;
    let mut token = String::new();
    let mut in_tag = false;

    for ch in content.chars() {
        token.push(ch);
        if ch == '<' {
            in_tag = true;
        }
        if in_tag && ch == '>' {
            let trimmed = token.trim();
            if trimmed.starts_with("</") {
                indent = indent.saturating_sub(1);
            }
            if !trimmed.is_empty() {
                out.push_str(&"  ".repeat(indent));
                out.push_str(trimmed);
                out.push('\n');
            }
            if trimmed.starts_with('<')
                && !trimmed.starts_with("</")
                && !trimmed.ends_with("/>")
                && !trimmed.starts_with("<!")
                && !trimmed.to_ascii_lowercase().starts_with("<meta")
                && !trimmed.to_ascii_lowercase().starts_with("<link")
                && !trimmed.to_ascii_lowercase().starts_with("<br")
            {
                indent += 1;
            }
            token.clear();
            in_tag = false;
        }
    }

    let tail = token.trim();
    if !tail.is_empty() {
        out.push_str(&"  ".repeat(indent));
        out.push_str(tail);
        out.push('\n');
    }
    out
}

// ── JavaScript token-aware beautifier ────────────────────────────────────────

/// Minimal token types for the JS beautifier.
#[derive(Debug, Clone, PartialEq)]
enum Tok {
    /// A string literal including both quote characters and all internal escapes (verbatim).
    Str(String),
    /// A template literal including backticks and all `${...}` expressions (verbatim).
    Template(String),
    /// A regex literal including slashes and flags (verbatim). Only emitted when can_regex is true.
    Regex(String),
    /// A line comment `// ...` (verbatim, no trailing newline).
    LineComment(String),
    /// A block comment `/* ... */` (verbatim).
    BlockComment(String),
    /// Any run of identifier/keyword/number characters.
    Word(String),
    /// `{` `[` `(` `)` `]` `}` `;` `,` — single meaningful punctuation characters.
    Punct(char),
    /// Multi-character operators: `=>`, `===`, `!==`, `>=`, `<=`, `**`, `&&`, `||`, `??`, `++`,
    /// `--`, `+=`, `-=`, `*=`, `/=`, `%=`, `**=`, `&&=`, `||=`, `??=`, `...`.
    Op(String),
}

/// Keywords after which a `/` starts a regex rather than a division operator.
const REGEX_STARTERS: &[&str] = &[
    "return", "typeof", "instanceof", "void", "delete", "throw", "new", "in", "of", "case",
    "yield", "await",
];

fn tokenize(content: &str) -> Vec<Tok> {
    let chars: Vec<char> = content.chars().collect();
    let len = chars.len();
    let mut i = 0;
    let mut tokens: Vec<Tok> = Vec::new();
    // After seeing one of these tokens, '/' starts a regex instead of division.
    let mut can_regex = true;

    macro_rules! peek {
        ($offset:expr) => {
            chars.get(i + $offset).copied()
        };
    }

    while i < len {
        let ch = chars[i];

        // ── skip plain whitespace (regenerated by printer) ────────────────────
        if ch.is_ascii_whitespace() {
            i += 1;
            continue;
        }

        // ── line comment ──────────────────────────────────────────────────────
        if ch == '/' && peek!(1) == Some('/') {
            let start = i;
            i += 2;
            while i < len && chars[i] != '\n' {
                i += 1;
            }
            tokens.push(Tok::LineComment(chars[start..i].iter().collect()));
            can_regex = false;
            continue;
        }

        // ── block comment ─────────────────────────────────────────────────────
        if ch == '/' && peek!(1) == Some('*') {
            let start = i;
            i += 2;
            while i + 1 < len && !(chars[i] == '*' && chars[i + 1] == '/') {
                i += 1;
            }
            i += 2; // consume */
            tokens.push(Tok::BlockComment(chars[start..i].iter().collect()));
            // block comments don't change regex context
            continue;
        }

        // ── regex literal ─────────────────────────────────────────────────────
        if ch == '/' && can_regex {
            let start = i;
            i += 1;
            let mut in_char_class = false;
            while i < len {
                let c = chars[i];
                if c == '\\' && i + 1 < len {
                    i += 2;
                    continue;
                }
                if c == '[' {
                    in_char_class = true;
                } else if c == ']' {
                    in_char_class = false;
                } else if c == '/' && !in_char_class {
                    i += 1;
                    break;
                } else if c == '\n' {
                    // unterminated regex — treat as division, backtrack
                    i = start + 1;
                    tokens.push(Tok::Punct('/'));
                    break;
                }
                i += 1;
            }
            // consume flags
            while i < len && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            tokens.push(Tok::Regex(chars[start..i].iter().collect()));
            can_regex = false;
            continue;
        }

        // ── string literal ────────────────────────────────────────────────────
        if ch == '"' || ch == '\'' {
            let quote = ch;
            let start = i;
            i += 1;
            while i < len {
                let c = chars[i];
                if c == '\\' && i + 1 < len {
                    i += 2;
                    continue;
                }
                if c == quote {
                    i += 1;
                    break;
                }
                i += 1;
            }
            tokens.push(Tok::Str(chars[start..i].iter().collect()));
            can_regex = false;
            continue;
        }

        // ── template literal (preserve verbatim including ${...} expressions) ─
        if ch == '`' {
            let start = i;
            i += 1;
            let mut depth: i32 = 0; // tracks nesting inside ${ }
            while i < len {
                let c = chars[i];
                if c == '\\' && i + 1 < len {
                    i += 2;
                    continue;
                }
                if c == '$' && peek!(1) == Some('{') {
                    depth += 1;
                    i += 2;
                    continue;
                }
                if c == '}' && depth > 0 {
                    depth -= 1;
                    i += 1;
                    continue;
                }
                if c == '`' && depth == 0 {
                    i += 1;
                    break;
                }
                i += 1;
            }
            tokens.push(Tok::Template(chars[start..i].iter().collect()));
            can_regex = false;
            continue;
        }

        // ── multi-char operators ──────────────────────────────────────────────
        {
            let two: String = chars[i..len.min(i + 2)].iter().collect();
            let three: String = chars[i..len.min(i + 3)].iter().collect();

            if three == "**=" || three == "&&=" || three == "||=" || three == "??=" || three == "..." {
                tokens.push(Tok::Op(three));
                i += 3;
                can_regex = true;
                continue;
            }
            if matches!(
                two.as_str(),
                "=>" | "===" | "!==" | ">=" | "<=" | "**" | "&&" | "||" | "??" | "++" | "--"
                    | "+=" | "-=" | "*=" | "/=" | "%=" | "==" | "!=" | "<<" | ">>"
            ) {
                let is_value = matches!(two.as_str(), "++" | "--");
                tokens.push(Tok::Op(two));
                i += 2;
                can_regex = !is_value;
                continue;
            }
        }

        // ── single punctuation that matters to the printer ────────────────────
        if matches!(ch, '{' | '}' | '[' | ']' | '(' | ')' | ';' | ',') {
            tokens.push(Tok::Punct(ch));
            can_regex = matches!(ch, '{' | '[' | '(' | ',' | ';');
            i += 1;
            continue;
        }

        // ── word / identifier / number ────────────────────────────────────────
        if ch.is_alphanumeric() || ch == '_' || ch == '$' || ch == '#' {
            let start = i;
            while i < len
                && (chars[i].is_alphanumeric()
                    || chars[i] == '_'
                    || chars[i] == '$'
                    || chars[i] == '#'
                    || chars[i] == '.')
            {
                i += 1;
            }
            let word: String = chars[start..i].iter().collect();
            let is_keyword = REGEX_STARTERS.contains(&word.as_str())
                || matches!(
                    word.as_str(),
                    "if" | "else" | "for" | "while" | "do" | "switch" | "try" | "catch"
                        | "finally" | "class" | "function" | "async" | "const" | "let" | "var"
                        | "import" | "export" | "default" | "extends" | "static"
                );
            can_regex = REGEX_STARTERS.contains(&word.as_str())
                || matches!(word.as_str(), "else" | "do" | "finally");
            tokens.push(Tok::Word(word));
            let _ = is_keyword;
            continue;
        }

        // ── anything else (operators, colon, dot, etc.) ───────────────────────
        tokens.push(Tok::Punct(ch));
        can_regex = matches!(
            ch,
            '=' | '!' | '<' | '>' | '+' | '-' | '*' | '/' | '%' | '&' | '|' | '^' | '~' | '?'
                | ':' | '.'
        );
        i += 1;
    }

    tokens
}

/// Keywords that should have a space after them when followed by `(` or `{`.
const SPACE_AFTER_KW: &[&str] = &[
    "if", "else", "for", "while", "do", "switch", "try", "catch", "finally", "return", "typeof",
    "instanceof", "void", "delete", "throw", "new", "in", "of", "case", "yield", "await",
    "class", "function", "async", "const", "let", "var", "import", "export", "extends", "static",
    "default",
];

fn print_tokens(tokens: &[Tok]) -> String {
    let mut out = String::with_capacity(tokens.len() * 4);
    let mut indent = 0usize;
    let mut paren_depth = 0usize; // inside () — commas here are arg separators, not stmt separators

    fn push_newline(out: &mut String, indent: usize) {
        // Trim trailing whitespace from the current line before adding newline
        while out.ends_with(' ') {
            out.pop();
        }
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&"  ".repeat(indent));
    }

    for (idx, tok) in tokens.iter().enumerate() {
        let next = tokens.get(idx + 1);

        match tok {
            Tok::Str(s) | Tok::Template(s) | Tok::Regex(s) => {
                out.push_str(s);
            }

            Tok::LineComment(s) => {
                out.push_str(s);
                push_newline(&mut out, indent);
            }

            Tok::BlockComment(s) => {
                out.push_str(s);
                out.push(' ');
            }

            Tok::Word(w) => {
                out.push_str(w);
                // Add space after keywords when the next non-trivial token warrants it
                if SPACE_AFTER_KW.contains(&w.as_str()) {
                    if !matches!(next, Some(Tok::Punct(';')) | Some(Tok::Punct(',')) | None) {
                        out.push(' ');
                    }
                }
            }

            Tok::Op(op) => {
                match op.as_str() {
                    "++" | "--" => out.push_str(op),
                    "=>" => {
                        out.push_str(" => ");
                    }
                    _ => {
                        out.push(' ');
                        out.push_str(op);
                        out.push(' ');
                    }
                }
            }

            Tok::Punct(ch) => match ch {
                '{' | '[' => {
                    out.push(*ch);
                    indent += 1;
                    push_newline(&mut out, indent);
                }
                '(' => {
                    out.push('(');
                    paren_depth += 1;
                }
                ')' => {
                    paren_depth = paren_depth.saturating_sub(1);
                    out.push(')');
                }
                '}' | ']' => {
                    indent = indent.saturating_sub(1);
                    push_newline(&mut out, indent);
                    out.push(*ch);
                    // After `}` or `]` we usually need a newline unless followed by specific tokens
                    match next {
                        Some(Tok::Punct(';'))
                        | Some(Tok::Punct(','))
                        | Some(Tok::Punct(')'))
                        | Some(Tok::Punct(']'))
                        | Some(Tok::Punct('}'))
                        | Some(Tok::Op(_))
                        | None => {}
                        _ => {
                            push_newline(&mut out, indent);
                        }
                    }
                }
                ';' => {
                    out.push(';');
                    push_newline(&mut out, indent);
                }
                ',' => {
                    out.push(',');
                    if paren_depth == 0 {
                        push_newline(&mut out, indent);
                    } else {
                        out.push(' ');
                    }
                }
                _ => {
                    out.push(*ch);
                }
            },
        }
    }

    // Ensure file ends with a newline
    while out.ends_with(' ') {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }

    out
}

fn beautify_javascript(content: &str) -> String {
    let tokens = tokenize(content);
    print_tokens(&tokens)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_template_literal() {
        let src = "const x=`hello ${name}`;";
        let out = beautify(AssetKind::JavaScript, src);
        assert!(out.contains("`hello ${name}`"), "got: {out}");
    }

    #[test]
    fn preserves_string_contents() {
        let src = r#"const x="hello\nworld";"#;
        let out = beautify(AssetKind::JavaScript, src);
        assert!(out.contains(r#""hello\nworld""#), "got: {out}");
    }

    #[test]
    fn indents_blocks() {
        let src = "function f(){return 1;}";
        let out = beautify(AssetKind::JavaScript, src);
        assert!(out.contains('\n'), "expected newlines in: {out}");
        assert!(out.contains("  "), "expected indentation in: {out}");
    }

    #[test]
    fn preserves_regex() {
        let src = "var re=/[a-z]+/gi;";
        let out = beautify(AssetKind::JavaScript, src);
        assert!(out.contains("/[a-z]+/gi"), "got: {out}");
    }
}
